version: '3'

services:
  app:
    build:
        context: .
    volumes:
      - ./application:/srv:rw,cached
      - ./docker/php/.ssh:/var/www/.ssh
      - ./docker/php/.composer:/var/www/.composer
#      - ./docker/php/www:/var/www/
#      - app_log:/srv/var/log
    ports:
      - "80:80"
  mongodb:
    build:
      context: ./docker/mongodb
      args:
        - mongodb_username=${MONGODB_USERNAME}
        - mongodb_password=${MONGODB_PASSWORD}
        - mongodb_initdb_database=${MONGO_INITDB_DATABASE}
    volumes:
      - mongo_data:/data/db
    env_file:
      - .env
    ports:
      - "27017:27017"

volumes:
  app_log:
  nginx_log:
  mongo_data:
