apiVersion: apps/v1
kind: Deployment
metadata:
    name: app
spec:
    selector:
        matchLabels:
            app: app
    replicas: 1
    template:
        metadata:
            labels:
                app: app
        spec:
            containers:
                - name: app
                  image: shashanknsdocker/php-nginx:latest
                  ports:
                      - containerPort: 80
                  env:
                      - name: MONGODB_URL
                        value: mongodb://snapper:snapper@database-service:27017/snapper
                      - name: MONGODB_DB
                        value: snapper
                  volumeMounts:
                      - name: config-volume
                        mountPath: /srv/.env.local
                        subPath: .env.local
                      - name: config-volume
                        mountPath: /etc/nginx/nginx.conf
                        subPath: nginx.conf
            volumes:
                - name: config-volume
                  configMap:
                      name: symfony-env
            imagePullSecrets:
                - name: regcred   # Image secret created using the command. Refer Readme for details.
