apiVersion: v1
kind: Service
metadata:
    name: application-service
spec:
    selector:
        app: app
    ports:
        - name: http
          protocol: TCP
          port: 80
          targetPort: 80
          nodePort: 30080
    type: NodePort
#  type: ClusterIP