apiVersion: v1
kind: Service
metadata:
  name: database-service
spec:
  selector:
     app: database
  ports:
  - port: 27017
    targetPort: 27017
    nodePort: 30081
  type: NodePort
#  type: ClusterIP

---

#apiVersion: v1
#kind: ConfigMap
#metadata:
#  name: mongodb-config
#data:
#  # MongoDB server configuration
#  mongodb.conf: |
#    storage:
#      dbPath: /data/db
#    net:
#      bindIp: 0.0.0.0
#      port: 27017
#  # MongoDB user credentials
#  mongodb-credentials.yml: |
#    users:
#    - name: admin
#      db: test_database
#      password: password
#      roles:
#      - readWrite

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
spec:
  selector:
    matchLabels:
      app: database
  replicas: 1
  template:
    metadata:
      labels:
        app: database
    spec:
#      volumes:
#        # Mount the MongoDB data directory
#        - name: mongodb-data
#          persistentVolumeClaim:
#            claimName: mongodb-pvc
#        # Mount the MongoDB configuration as a file
#        - name: mongodb-config
#          configMap:
#            name: mongodb-config
#            items:
#              - key: mongodb.conf
#                path: mongodb.conf
        # Mount the MongoDB user credentials as a file
#        - name: mongodb-credentials
#          configMap:
#            name: mongodb-config
#            items:
#              - key: mongodb-credentials.yml
#                path: mongodb-credentials.yml
      containers:
        - name: database
          image: mongo:5
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: password
              #The following credentials will create a new user in mongodb for the mentioned db
            - name: MONGO_USERNAME
              value: admin
            - name: MONGO_PASSWORD
              value: password
            - name: MONGO_DBNAME
              value: test_database