---

apiVersion: v1
kind: Service
metadata:
  name: database-service
spec:
  selector:
    app: database
  ports:
    - name: database
      port: 27017
      targetPort: 27017
      protocol: TCP
      nodePort: 30081
  type: NodePort
#  clusterIP: None

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: database-configmap
data:
  mongodb-config: |-
    rs.initiate({
      _id: "rs0",
      members: [
        { _id: 0, host: "database-0.database-service" },
        { _id: 1, host: "database-1.database-service" },
        { _id: 2, host: "database-2.database-service" }
      ]
    })

---


apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database
spec:
  serviceName: database
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: mongodb
          image: mongo:5
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: password
          ports:
            - name: mongodb
              containerPort: 27017
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
            - name: shared-config
              mountPath: /shared-config
#          command: [ "mongod" ]
#          args: [ "--replSet", "rs0" ]
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: database-pvc
        - name: shared-config
          configMap:
            name: database-configmap
---

