apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  selector:
    matchLabels:
      app: app
  replicas: 1
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: shashanknsdocker/php-nginx:latest
          imagePullPolicy: Always
          command:
            - "app"
          ports:
            - containerPort: 80
          env:
            - name: MONGODB_URL
              value: mongodb://mongodb-0.mongodb:27017/?replicaSet=rs0
            - name: MONGODB_DB
              value: zimble
            - name: redis_url
              value: redis://redis-service
          volumeMounts:
            - name: config-volume
              mountPath: /srv/.env.local
              subPath: .env.local
            - name: config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
          resources:
            requests:
              memory: "2Gi"
              cpu: "2"
            limits:
              memory: "4Gi"
              cpu: "4"
      volumes:
        - name: config-volume
          configMap:
            name: app-config
      imagePullSecrets:
        - name: regcred   # Image secret created using the command. Refer Readme for details.
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue
spec:
  selector:
    matchLabels:
      app: queue
  replicas: 1
  template:
    metadata:
      labels:
        app: queue
    spec:
      containers:
        - name: queue
          image: shashanknsdocker/php-nginx:latest
          imagePullPolicy: Always
          command:
            - "queue"
          ports:
            - containerPort: 80
          env:
            - name: MONGODB_URL
              value: mongodb://mongodb-0.mongodb:27017/?replicaSet=rs0
            - name: MONGODB_DB
              value: zimble
            - name: redis_url
              value: redis://redis-service
          volumeMounts:
            - name: config-volume
              mountPath: /srv/.env.local
              subPath: .env.local
            - name: config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
          resources:
            requests:
              memory: "2Gi"
              cpu: "2"
            limits:
              memory: "4Gi"
              cpu: "4"
      volumes:
        - name: config-volume
          configMap:
            name: app-config
      imagePullSecrets:
        - name: regcred   # Image secret created using the command. Refer Readme for details.
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler
spec:
  selector:
    matchLabels:
      app: scheduler
  replicas: 1
  template:
    metadata:
      labels:
        app: scheduler
    spec:
      containers:
        - name: scheduler
          image: shashanknsdocker/php-nginx:latest
          imagePullPolicy: Always
          command:
            - "scheduler"
          ports:
            - containerPort: 80
          env:
            - name: MONGODB_URL
              value: mongodb://mongodb-0.mongodb:27017/?replicaSet=rs0
            - name: MONGODB_DB
              value: zimble
            - name: redis_url
              value: redis://redis-service
          volumeMounts:
            - name: config-volume
              mountPath: /srv/.env.local
              subPath: .env.local
            - name: config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
          resources:
            requests:
              memory: "2Gi"
              cpu: "2"
            limits:
              memory: "4Gi"
              cpu: "4"
      volumes:
        - name: config-volume
          configMap:
            name: app-config
      imagePullSecrets:
        - name: regcred   # Image secret created using the command. Refer Readme for details.